name: Orizuru
description: Web-based communication plugin for Minecraft servers using events.
version: 1.1.3-dottwelve
author: GaryCraft
main: xyz.ourspace.xdev.Orizuru
api-version: "1.12.2"
depend: [Vault]
commands:
  orizuru:
    description: Gets Info about the plugin
    usage: /<command>
  .ping:
    description: Get your ping
    usage: /<command> <uuid>

